app/containers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, DateTimeField, SelectField, DecimalField, BooleanField
from wtforms.validators import DataRequired, InputRequired, Length
from wtforms.fields import DateField

class ContainerAddForm(FlaskForm):
    name = StringField(u'Container Name')
    containertype_id = SelectField(u'Container Type', [InputRequired()])
    volume_actual = DecimalField(u'Actual Volume', [InputRequired()])
    time_created = DateTimeField(u'Create Time')
    submit = SubmitField(u'Create Container')

class VesselMoveContentsForm(FlaskForm):
    name = SelectField(u'New Vessel', [InputRequired()])
    submit = SubmitField(u'Move Contents')

class VesselUpdateStatusForm(FlaskForm):
    name = StringField(u'Vessel Name', [InputRequired()], render_kw={'readonly': True})
    status_id = SelectField(u'Vessel Status', [InputRequired()])
    submit = SubmitField(u'Update Status')

class VesselFillForm(FlaskForm):
    name = SelectField(u'Vessel', [InputRequired()])
    submit = SubmitField(u'Fill Vessel')

app/containers/__init__.py
from flask import Blueprint

containers = Blueprint('containers', __name__)

from .views import containers
from app.main import errors

app/containers/views.py
from flask import Blueprint, render_template, session, redirect, url_for, current_app, flash
#from werkzeug.wrappers import StreamOnlyMixin
from .. import db
from ..models import Container, Containertype, Status, Batch
from . import containers
from .forms import ContainerAddForm, VesselMoveContentsForm, VesselUpdateStatusForm, VesselFillForm
from datetime import datetime

_label_base_url = "http://"+"dabl.local"

@containers.route('/container_overview', methods=['GET', 'POST'])
def all_containers():
    _all_containers = Container.query.join(Container.containertype_rel)\
        .all()
        #.filter(Vessel.status_id != 199)\
        #.all()
    return render_template('containers/container_overview.html',
                           all_containers=_all_containers)

@containers.route('/container_overview/active', methods=['GET', 'POST'])
def active_containers():
    _active_containers = Container.query.join(Container.containertype_rel)\
        .filter(Container.status_id == 200)\
        .all()
    return render_template('containers/container_overview.html',
                           all_containers=_active_containers)

@containers.route('/container_add/<batch_name>', methods=['GET', 'POST'])
def container_add(batch_name):
    _container = Container()
    _batch = Batch.query.filter_by(name=batch_name).first()

    count_batch_containers = Container.query.filter_by(batch_id=_batch.id).count()
    container_next = count_batch_containers + 1 
    time_now = datetime.now()

    _container.batch_id = _batch.id
    _container.name = 'C' + str(container_next).zfill(2) + '[' + batch_name + ']'
    _container.time_created = time_now

    form = ContainerAddForm(obj=_container)
    form.containertype_id.choices = [(row.id, row.name) for row in Containertype.query.all()]

    if form.validate_on_submit():
        _container.time_created = time_now
        _container.status_id = 200
        form.populate_obj(_container)

        db.session.add(_container)
        db.session.commit()

        db.session.refresh(_container)
        flash('Container added.', 'success')
        return redirect(url_for('batches.batch_view', name=_batch.name))
    
    return render_template('containers/container_add.html',
                           form=form,
                           container=_container)


@containers.route('/container_lookup/<container_id>', methods=['GET', 'POST'])
def container_lookup(container_id):
    _all_containers = Container.query.join(Container.containertype_rel).all()
    _container = Container.query.join(Container.containertype_rel).filter(Container.id==container_id).first()

    if _container.batch_id:
        return redirect(url_for('batches.batch_view', name=_container.batch.name))
    
    flash('Container not associated with batch.', 'success')
    return redirect(url_for('containers.all_containers'))


@containers.route('/container_label/<container_id>', methods=['GET', 'POST'])
def container_label(container_id):
    
    _container = Container.query.join(Container.containertype_rel).filter(Container.id==container_id).first()

    return render_template('containers/container_label.html',
                           container=_container,
                           base_url = _label_base_url)


@containers.route('/container_consume/<container_id>', methods=['GET', 'POST'])
def container_consume(container_id):
    
    _container = Container.query.join(Container.containertype_rel).filter(Container.id==container_id).first()

    if _container.status_id == 200:
        _container.status_id = 202
        db.session.add(_container)
        db.session.commit()
        db.session.refresh(_container)
        flash('Container Consumed.', 'success')
        return redirect(url_for('containers.active_containers'))
    else:
        flash('Container Consumption Failed.', 'danger')
        return redirect(url_for('containers.active_containers'))



# @containers.route('/vessel_move_contents/<container_id>', methods=['GET', 'POST'])
# def vessel_move_contents(container_id):
#     _all_vessels = Container.query.join(Container.containertype_rel) \
#         .filter(Containertype.is_vessel.is_(True)) \
#         .filter(Container.status_id == 100) \
#         .filter((Container.batch_id.is_(None) | Container.batch_id.is_('')))\
#         .all()
#     _current_vessel = Container.query.join(Container.containertype_rel).filter(Container.id==container_id).first()
#     _batch = Batch.query.filter_by(id=_current_vessel.batch_id).first()

#     form = VesselMoveContentsForm()

#     form.name.choices = [(row.id, row.name) for row in _all_vessels]

#     if form.validate_on_submit():
        
#         new_vessel_id = form.name.data
#         _new_vessel = Container.query.join(Container.containertype_rel).filter(Container.id==new_vessel_id).first()
#         _new_vessel.batch_id = _current_vessel.batch_id
#         _new_vessel.status_id = 102 
#         _current_vessel.batch_id = ''
#         _current_vessel.status_id = 101

#         db.session.add(_new_vessel)
#         db.session.commit()

#         db.session.refresh(_new_vessel)
#         flash('Vessel contents moved.', 'success')
#         return redirect(url_for('containers.all_vessels'))
    
#     return render_template('containers/vessel_move_contents.html',
#                            form=form,
#                            vessel=_current_vessel,
#                            batch=_batch)


# @containers.route('/vessel_update_status/<container_id>', methods=['GET', 'POST'])
# def vessel_update_status(container_id):
#     _vessel = Container.query.join(Container.containertype_rel).filter(Container.id==container_id).first()
    
#     form = VesselUpdateStatusForm(obj=_vessel)

#     form.status_id.choices = [(row.id, row.name) for row in Status.query.filter_by(type='Container').all()]

#     if form.validate_on_submit():
#         form.populate_obj(_vessel)
#         db.session.add(_vessel)
#         db.session.commit()

#         db.session.refresh(_vessel)
#         flash('Vessel status updated.', 'success')
#         return redirect(url_for('containers.all_vessels'))
    
#     return render_template('containers/vessel_update_status.html',
#                            form=form,
#                            vessel=_vessel)


# @containers.route('/vessel_fill/<batch_id>', methods=['GET', 'POST'])
# def vessel_fill(batch_id):
#     _all_vessels = Container.query.join(Container.containertype_rel) \
#         .filter(Containertype.is_vessel.is_(True)) \
#         .filter(Container.status_id == 100) \
#         .filter((Container.batch_id.is_(None) | Container.batch_id.is_('')))\
#         .all()
#     _batch = Batch.query.filter_by(id=batch_id).first()
    
#     form = VesselFillForm()

#     form.name.choices = [(row.id, row.name) for row in _all_vessels]

#     if form.validate_on_submit():
#         _vessel = Container.query.join(Container.containertype_rel).filter(Container.id==form.name.data).first()
#         _vessel.batch_id = batch_id
#         _vessel.status_id = 102 
#         db.session.add(_vessel)
#         db.session.commit()

#         db.session.refresh(_vessel)
#         flash('Vessel status updated.', 'success')
#         return redirect(url_for('batches.batch_view', name=_batch.name))
    
#     return render_template('containers/vessel_fill.html',
#                            form=form,
#                            batch=_batch)

app/templates/containers/container_add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Add Container</b></h2> 


{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/containers/container_label.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

{% set link = base_url + '/container_lookup/'+ container.id|string %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-1">
            <img src="{{ qrcode(link, box_size=3) }}">
        </div>
        <div class="col-sm-3">
            <p>{{ container.name }}</p>
            <p>{{ container.batch.description }} | {{ container.batch.abv }}% ABV</p>
            <p>Bottled: {{ container.time_created.strftime('%Y-%m-%d') }}</p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/containers/container_overview.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% set base_url ="http://"+"192.168.1.101:5000" %}
{% block title %}DABL{% endblock %}

{% block page_content %}
<a id="btn_batch_add" type="button" href="{{ url_for('containers.active_containers') }}" class="btn btn-primary">Active</a>
<a id="btn_batch_add" type="button" href="{{ url_for('containers.all_containers') }}" class="btn btn-primary">All</a>
<div class="container">
    <div class="row mt-5">
      <div class="col-6 offset-3">
        <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Type</th>
                          <th>Volume</th>
                          <th>Age</th>
                          <th>Batch</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% if all_containers|length > 0 %}
                          {% for container in all_containers %}
                          {% set link = base_url + '/container_lookup/'+ container.id|string %}
                          <tr>
                            <td>{{ container.name }}</td>
                            <td>{{ container.containertype_rel.name }}</td>
                            <td>{{ container.volume_actual }} mL</td>
                            <td>{{ container.get_age() }} days</td>
                            <td><a href="{{ url_for('batches.batch_view', name=container.batch.name) }}">{{ container.batch.name }}</a></td>
                            <td><div class="btn-group" role="group" aria-label="Actions">
                              <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalCenterLabel{{container.id}}">
                                Label
                              </button>
                              <!-- Modal -->
                              <div class="modal fade" id="modalCenterLabel{{container.id}}">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="modalCenterLabel{{container.id}}">Container Label</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                      <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <img src="{{ qrcode(link, box_size=3) }}">
                                            </div>
                                            <div class="col-md-5">
                                                <p>{{ container.name }}</p>
                                                <p>{{ container.batch.description }} | {{ container.batch.abv }}% ABV</p>
                                                <p>Bottled: {{ container.time_created.strftime('%Y-%m-%d') }}</p>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!-- https://stackoverflow.com/questions/45874906/flask-and-javascript-confirm-before-deleting -->
                              <!--  https://stackoverflow.com/questions/70257299/flask-modal-confirm-dialog look at this example to align confirms-->
                              <!-- Button trigger modal -->
                              {% if container.status_id == 200 %}
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter{{container.id}}">
                                Consume
                              </button>
                              <!-- Modal -->
                              <div class="modal fade" id="exampleModalCenter{{container.id}}">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLongTitle{{container.id}}">Container Consumption</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                      <h3>Consume {{container.name}}</h3>
                                      <p>Are you sure?</p>
                                    </div>
                                    <div class="modal-footer">
                                      <form action="{{url_for('containers.container_consume', container_id=container.id)}}" method="post">
                                        <input type="submit" value="Consume" class="btn btn-primary mr-auto">
                                      </form>
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              {% endif %}


                            </td>
                            </div>
                          </td>
                          </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <td>No Containers Added. Please add a container.</a></td><td></td>
                          </tr>
                        {% endif %}
                      </tbody>
                    </table>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/containers/vessel_move_contents.html
{% extends "base.html" %}


{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Move Vessel Contents</b></h2> 

<p><b>Batch:</b></p>
<p>{{ batch.name }}</p>

<p><b>Current Vessel:</b></p>
<p>{{ vessel.name }}</p>

{{ wtf.quick_form(form) }}
{% endblock %}