app/batches/__init__.py
from app.main import views, errors

app/batches/views.py
from flask import Blueprint, render_template, session, redirect, url_for, current_app
from .. import db
from ..models import Batch

batches1 = Blueprint('batches', __name__)

@batches1.route('/batch_overview1', methods=['GET', 'POST'])
def all_batches():
    print('all_batches function 2 executed')
    _all_batches = Batch.query.all()

    return render_template('batches/batch_overview.html',
                           all_batches=_all_batches)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
batches = Blueprint('batches', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, current_app, flash
from .. import db
from ..models import Measurement, User, Batch, Action, Brewtype, Brewstyle, Status, Container, Containertype, Vessel
from ..email import send_email
from . import main, batches
from .forms import NameForm, BatchAddForm, BatchEditForm, BatchMoveForm
from datetime import datetime



@main.route('/', methods=['GET', 'POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        if user is None:
            user = User(username=form.name.data)
            db.session.add(user)
            db.session.commit()
            session['known'] = False
            if current_app.config['FLASKY_ADMIN']:
                send_email(current_app.config['FLASKY_ADMIN'], 'New User',
                           'mail/new_user', user=user)
        else:
            session['known'] = True
        session['name'] = form.name.data
        return redirect(url_for('.index'))
    return render_template('index.html',
                           form=form, name=session.get('name'),
                           known=session.get('known', False))



@batches.route('/batch_overview', methods=['GET', 'POST'])
def all_batches():
    _all_batches = Batch.query.all()

    return render_template('batch_overview.html',
                           all_batches=_all_batches)


@batches.route('/batch_add', methods=['GET', 'POST'])
def batch_add():
    form = BatchAddForm()
    _batch = Batch()
  
    time_now = datetime.now()
    form.time_start.data = time_now

    form.type_id.choices = [(row.id, row.name) for row in Brewtype.query.all()]
    form.style_id.choices = [(row.id, row.name) for row in Brewstyle.query.all()]


    if form.validate_on_submit():
        _batch.time_updated = time_now
        _batch.status_id = 1000
        form.populate_obj(_batch)
        db.session.add(_batch)
        db.session.commit()

        db.session.refresh(_batch)
        flash('Batch added.', 'success')
        return redirect(url_for('batches.all_batches'))
    
    return render_template('batch_add.html',
                           form=form,
                           batch=_batch)


@batches.route('/batch_move/<batch_name>', methods=['GET', 'POST'])
def batch_move(batch_name):
    _batch = Batch.query.filter_by(name=batch_name).first()
    _vessels = Container.query.join(Container.containertype_rel).filter(Containertype.is_vessel.is_(True), Container.batch_id==_batch.id).all
    _all_vessels = Container.query.join(Container.containertype_rel).filter(Containertype.is_vessel.is_(True)).all()


    form = BatchMoveForm(obj=_batch)

    time_now = datetime.now()

    form.type_id.choices = [(row.id, row.name) for row in Brewtype.query.all()]
    form.style_id.choices = [(row.id, row.name) for row in Brewstyle.query.all()]
    form.status_id.choices = [(row.id, row.name) for row in Status.query.filter_by(type='Batch').all()]
    form.status_id.choices = [(row.id, row.name) for row in Status.query.filter_by(type='Batch').all()]

    if form.validate_on_submit():
        _batch.time_updated = time_now
        form.populate_obj(_batch)
        db.session.add(_batch)
        db.session.commit()

        db.session.refresh(_batch)
        flash('Batch updated.', 'success')
        return redirect(url_for("batches.all_batches"))
    
    return render_template('batch_move.html',
                           form=form,
                           batch=_batch)


@batches.route('/batch_edit/<batch_name>', methods=['GET', 'POST'])
def batch_edit(batch_name):
    _batch = Batch.query.filter_by(name=batch_name).first()
    
    form = BatchEditForm(obj=_batch)

    time_now = datetime.now()

    form.type_id.choices = [(row.id, row.name) for row in Brewtype.query.all()]
    form.style_id.choices = [(row.id, row.name) for row in Brewstyle.query.all()]
    form.status_id.choices = [(row.id, row.name) for row in Status.query.filter_by(type='Batch').all()]

    if form.validate_on_submit():
        _batch.time_updated = time_now
        form.populate_obj(_batch)
        db.session.add(_batch)
        db.session.commit()

        db.session.refresh(_batch)
        flash('Batch updated.', 'success')
        return redirect(url_for('batches.all_batches'))
    
    return render_template('batch_edit.html',
                           form=form,
                           batch=_batch)


@batches.route('/batch_view/<name>', methods=['GET', 'POST'])
def batch_view(name):
    _batch = Batch.query.filter_by(name=name).first()
    _measurements = Measurement.query.filter_by(batch_id=_batch.id).all()
    _actions = Action.query.filter_by(batch_id=_batch.id).all()
    _vessels = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.batch_id==_batch.id).first()
    _containers = Container.query.join(Container.containertype_rel).filter(Container.batch_id==_batch.id).all()

    if not _batch:
        flash('Oops! Something went wrong!.', 'danger')
        return redirect(url_for('batches.all_batches'))

    return render_template('batch_view.html',
                           batch=_batch, 
                           measurements=_measurements,
                           actions=_actions,
                           vessels=_vessels,
                           containers=_containers)


@batches.route('/batch_view_enhance/<name>', methods=['GET', 'POST'])
def batch_view_enhance(name):
    _batch = Batch.query.filter_by(name=name).first()
    _measurements = Measurement.query.filter_by(batch_id=_batch.id).all()
    _actions = Action.query.filter_by(batch_id=_batch.id).all()
    _vessels = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.batch_id==_batch.id).first()
    _containers = Container.query.join(Container.containertype_rel).filter(Container.batch_id==_batch.id).all()

    if not _batch:
        flash('Oops! Something went wrong!.', 'danger')
        return redirect(url_for('batches.all_batches'))

    return render_template('batch_view_enhance.html',
                           batch=_batch, 
                           measurements=_measurements,
                           actions=_actions,
                           vessels=_vessels,
                           containers=_containers)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}DABL{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">DABL</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('batches.all_batches') }}">Batch Overview</a></li>
                <li><a href="{{ url_for('vessels.all_vessels') }}">Vessel Overview</a></li>
                <li><a href="{{ url_for('containers.active_containers') }}">Container Overview</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/batch_add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Add Batch</b></h2> 


{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/batch_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Edit Batch</b></h2> 


{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/batch_move.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Move Batch</b></h2> 


{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/batch_overview.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}
<a id="btn_batch_add" type="button" href="{{ url_for('batches.batch_add') }}" class="btn btn-primary">Add Batch</a>
<div class="container">
    <div class="row mt-5">
      <div class="col-6 offset-3">
        <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Batches</th>
                          <th>Start Date</th>
                          <th>Type</th>
                          <th>Style</th>
                          <th>Status</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% if all_batches|length > 0 %}
                          {% for batch in all_batches %}
                          <tr>
                            <td>{{ batch.name }}</td>
                            <td>{{ batch.time_start.strftime('%Y-%m-%d') }}</td>
                            <td>{{ batch.type.name }}</td>
                            <td>{{ batch.style.name }}</td>
                            <td>{{ batch.status.name }}</td>
                            <td><div class="btn-group" role="group" aria-label="Task Actions">
                              <a style="margin-right: 5px; margin-left: 5px;" class="btn btn-outline-primary" href="{{ url_for('batches.batch_view', name=batch.name) }}">View</a>
                              <a style="margin-right: 5px; margin-left: 5px;" class="btn btn-outline-secondary" href="{{ url_for('batches.batch_edit', batch_name=batch.name) }}">Edit</a>
                            </div>
                          </td>
                          </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <td>No Batches Added. Please <a href="{{ url_for('batches.batch_add')}}">add a batch</a></td><td></td>
                          </tr>
                        {% endif %}
                      </tbody>
                    </table>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/batch_view enhance.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}">
<h1 class="h1"><b>Batch {{ batch.name }}</b></h1> 

<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Type:</b></td>
          <td>{{ batch.type.name }}</td>
        </tr>
        <tr>
          <td><b>Style:</b></td>
          <td>{{ batch.style.name }}</td>
        </tr>
          <td><b>Status:</b></td>
          <td>{{ batch.status.name }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Start Date:</b></td>
          <td>{{ batch.time_start.strftime('%Y-%m-%d') }}</td>
        </tr>
        <tr>
          <td><b>End Date:</b></td>
          <td>{{ batch.time_end.strftime('%Y-%m-%d') }}</td>
        </tr>
          <td><b>Last Updated:</b></td>
          <td>{{ batch.time_updated }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<h2 class="h2"><b>Actions</b></h2>  
<a id="Enter" type="button" href="{{ url_for('actions.action_add', batch_name=batch.name) }}" class="btn btn-primary">Add Action</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Action Type</th>
    </tr>
  </thead>
  <tbody>
    {% if actions|length > 0 %}
      {% for action in actions %}
      <tr>
        <td>{{ action.time_performed.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{action.actiontype_rel.name }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Actions Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>

<h2 class="h2"><b>Measurements</b></h2> 
<a id="Enter" type="button" href="{{ url_for('measurements.measurement_add', batch_name=batch.name) }}" class="btn btn-primary">Add Measurement</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Measurement Type</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    {% if measurements|length > 0 %}
      {% for measurement in measurements %}
      <tr>
        <td>{{ measurement.time_measured.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{ measurement.measurmenttype_rel.name }}</td>
        <td>{{ measurement.value }} {{ measurement.measurmenttype_rel.eng_units }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Measurements Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>
<div class="page-content page-container" id="page-content">
  <div class="padding">
      <div class="row">
          <div class="col-lg-6">
                        {% if measurements|length > 0 %}
                          {% for measurement in measurements %}
                          <div class="tl-item">
                            <div class="tl-dot b-primary"></div>
                            <div class="tl-content">
                                <div class="">{{ measurement.measurmenttype_rel.name }} {{ measurement.value }} {{ measurement.measurmenttype_rel.eng_units }}</div>
                                <div class="tl-date text-muted mt-1">{{ measurement.time_measured.strftime('%Y-%m-%d %H:%M:%S') }}</div>
                            </div>
                          </div>  
                        {% endfor %}
                        {% else %}
                            <p>No Batches Added. Please <a href="{{ url_for('batches.add_batch')}}">add a batch</a></p>
                        {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/batch_view.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}
<h1 class="h1"><b>Batch {{ batch.name }}</b></h1> 

<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Type:</b></td>
          <td>{{ batch.type.name }}</td>
        </tr>
        <tr>
          <td><b>Style:</b></td>
          <td>{{ batch.style.name }}</td>
        </tr>
          <td><b>Status:</b></td>
          <td>{{ batch.status.name }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Start Date:</b></td>
          <td>{{ batch.time_start.strftime('%Y-%m-%d') }}</td>
        </tr>
        <tr>
          <td><b>End Date:</b></td>
          <td>
            {% if batch.time_end is not none %}
              {{ batch.time_end.strftime('%Y-%m-%d') }}
            {% else %}
              Ongoing
            {% endif %}
          </td>
        </tr>
        <tr>
          <td><b>Batch Age:</b></td>
          <td>{{ batch.get_age()}} days</td>
        </tr>
        <tr>
          <td><b>Last Updated:</b></td>
          <td>{{ batch.time_updated.strftime('%Y-%m-%d %H:%M:%S')}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Vessel</b></td>
          {% if vessels.name is defined %}
            <td>{{ vessels.name }} - <a href="{{ url_for('vessels.vessel_move_contents', vessel_id=vessels.id) }}"> Move Contents</a></td>
          {% else %}
            <td>None - <a href="{{ url_for('vessels.vessel_fill', batch_id=batch.id) }}"> Fill Vessel</a></td>
          {% endif %}
        </tr>
          {% if vessels.name is defined %}
          <td><b>Time in Vessel</b></td>
          <td>{{ batch.get_age()}} days</td>
          {% endif %}
        </tr>
      </tbody>
    </table>
  </div>
</div>

<h2 class="h2"><b>Containers</b></h2>  
<a id="btn_action_add" type="button" href="{{ url_for('containers.container_add', batch_name=batch.name) }}" class="btn btn-primary">Add Container</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    {% if containers|length > 0 %}
      {% for container in containers %}
      <tr>
        <td>{{ container.name }}</td>
        <td>{{ container.containertype_rel.name }}</td>
        <td>{{ container.volume_actual }}</td>
        <td>{{ container.get_age() }} days</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Actions Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>

<h2 class="h2"><b>Actions</b></h2>  
<a id="btn_action_add" type="button" href="{{ url_for('actions.action_add', batch_name=batch.name) }}" class="btn btn-primary">Add Action</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Action Type</th>
    </tr>
  </thead>
  <tbody>
    {% if actions|length > 0 %}
      {% for action in actions %}
      <tr>
        <td>{{ action.time_performed.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{action.actiontype_rel.name }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Actions Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>

<h2 class="h2"><b>Measurements</b></h2> 
<a id="btn_measurement_add" type="button" href="{{ url_for('measurements.measurement_add', batch_name=batch.name) }}" class="btn btn-primary">Add Measurement</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Measurement Type</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    {% if measurements|length > 0 %}
      {% for measurement in measurements %}
      <tr>
        <td>{{ measurement.time_measured.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{ measurement.measurmenttype_rel.name }}</td>
        <td>{{ measurement.value }} {{ measurement.measurmenttype_rel.eng_units }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Measurements Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>

{% endblock %}

app/templates/batch_view_enhance.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}">
<h1 class="h1"><b>Batch {{ batch.name }}</b></h1> 

<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Type:</b></td>
          <td>{{ batch.type.name }}</td>
        </tr>
        <tr>
          <td><b>Style:</b></td>
          <td>{{ batch.style.name }}</td>
        </tr>
          <td><b>Status:</b></td>
          <td>{{ batch.status.name }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><b>Start Date:</b></td>
          <td>{{ batch.time_start.strftime('%Y-%m-%d') }}</td>
        </tr>
        <tr>
          <td><b>End Date:</b></td>
          <td>{{ batch.time_end.strftime('%Y-%m-%d') }}</td>
        </tr>
          <td><b>Last Updated:</b></td>
          <td>{{ batch.time_updated }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<h2 class="h2"><b>Actions</b></h2>  
<a id="Enter" type="button" href="{{ url_for('actions.action_add', batch_name=batch.name) }}" class="btn btn-primary">Add Action</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Action Type</th>
    </tr>
  </thead>
  <tbody>
    {% if actions|length > 0 %}
      {% for action in actions %}
      <tr>
        <td>{{ action.time_performed.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{action.actiontype_rel.name }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Actions Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>

<h2 class="h2"><b>Measurements</b></h2> 
<a id="Enter" type="button" href="{{ url_for('measurements.measurement_add', batch_name=batch.name) }}" class="btn btn-primary">Add Measurement</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Time</th>
      <th>Measurement Type</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    {% if measurements|length > 0 %}
      {% for measurement in measurements %}
      <tr>
        <td>{{ measurement.time_measured.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        <td>{{ measurement.measurmenttype_rel.name }}</td>
        <td>{{ measurement.value }} {{ measurement.measurmenttype_rel.eng_units }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td>No Measurements Added.</td><td></td>
      </tr>
    {% endif %}
  </tbody>
</table>
<div class="page-content page-container" id="page-content">
  <div class="padding">
      <div class="row">
          <div class="col-lg-6">
                        {% if measurements|length > 0 %}
                          {% for measurement in measurements %}
                          <div class="tl-item">
                            <div class="tl-dot b-primary"></div>
                            <div class="tl-content">
                                <div class="">{{ measurement.measurmenttype_rel.name }} {{ measurement.value }} {{ measurement.measurmenttype_rel.eng_units }}</div>
                                <div class="tl-date text-muted mt-1">{{ measurement.time_measured.strftime('%Y-%m-%d %H:%M:%S') }}</div>
                            </div>
                          </div>  
                        {% endfor %}
                        {% else %}
                            <p>No Batches Added. Please <a href="{{ url_for('batches.add_batch')}}">add a batch</a></p>
                        {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL - Dashboard{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Dashboard</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Hello, are you ready to DABL?</h1>
    <a id="Enter" type="button" href="{{ url_for('batches.all_batches') }}" class="btn btn-primary">YES</a>
    <a id="Enter" type="button" href="{{ url_for('batches.all_batches') }}" class="btn btn-danger">NO</a>

</div>

{{ wtf.quick_form(form) }}

<p>Test QR</p>
<img src="{{ qrcode("DABL") }}">

{% endblock %}