app/vessels/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, DateTimeField, SelectField, DecimalField, BooleanField
from wtforms.validators import DataRequired, InputRequired, Length
from wtforms.fields import DateField

class VesselCreateForm(FlaskForm):
    name = StringField(u'Vessel Name', [InputRequired()])
    vesseltype_id = SelectField(u'Container Type', [InputRequired()])
    volume_actual = DecimalField(u'Actual Volume', [InputRequired()])
    submit = SubmitField(u'Create Vessel')

class VesselMoveContentsForm(FlaskForm):
    name = SelectField(u'New Vessel', [InputRequired()])
    submit = SubmitField(u'Move Contents')

class VesselUpdateStatusForm(FlaskForm):
    name = StringField(u'Vessel Name', [InputRequired()], render_kw={'readonly': True})
    status_id = SelectField(u'Vessel Status', [InputRequired()])
    submit = SubmitField(u'Update Status')

class VesselFillForm(FlaskForm):
    name = SelectField(u'Vessel', [InputRequired()])
    submit = SubmitField(u'Fill Vessel')

app/vessels/__init__.py
from flask import Blueprint

vessels = Blueprint('vessels', __name__)

from .views import vessels
from app.main import errors

app/vessels/views.py
from flask import Blueprint, render_template, session, redirect, url_for, current_app, flash
#from werkzeug.wrappers import StreamOnlyMixin
from .. import db
from ..models import Container, Containertype, Vessel, Vesseltype, Status, Batch
from . import vessels
from .forms import VesselMoveContentsForm, VesselUpdateStatusForm, VesselFillForm, VesselCreateForm
from datetime import datetime

_label_base_url = "http://"+"192.168.1.101:5000"

@vessels.route('/vessel_overview', methods=['GET', 'POST'])
def all_vessels():
    _all_vessels = Vessel.query.join(Vessel.vesseltype_rel)\
        .all()
        #.filter(Vessel.status_id != 199)\
        #.all()
    return render_template('vessels/vessel_overview.html',
                           all_vessels=_all_vessels)


@vessels.route('/vessel_create', methods=['GET', 'POST'])
def vessel_create():
    form = VesselCreateForm()
    _vessel = Vessel()
    form.vesseltype_id.choices = [(row.id, row.name) for row in Vesseltype.query.all()]

    count_vessels = Vessel.query.count()
    vessel_next = count_vessels + 1

    _vessel.name = 'Vessel' + str(vessel_next).zfill(2)

    if form.validate_on_submit():
        form.populate_obj(_vessel)
        db.session.add(_vessel)
        db.session.commit()

        db.session.refresh(_vessel)
        flash('Vessel created.', 'success')
        return redirect(url_for("vessels.all_vessels"))
    
    return render_template('vessels/vessel_create.html',
                           form=form,
                           vessel=_vessel)


@vessels.route('/vessel_lookup/<vessel_id>', methods=['GET', 'POST'])
def vessel_lookup(vessel_id):
    _all_vessels = Vessel.query.join(Vessel.vesseltype_rel).all()
    _vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==vessel_id).first()

    if _vessel.batch_id:
        return redirect(url_for('batches.batch_view', name=_vessel.batch.name))
    
    flash('Vessel not associated with batch.', 'success')
    return redirect(url_for('vessels.all_vessels'))


@vessels.route('/vessel_label/<vessel_id>', methods=['GET', 'POST'])
def vessel_label(vessel_id):
    
    _vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==vessel_id).first()

    return render_template('vessels/vessel_label.html',
                           vessel=_vessel,
                           base_url = _label_base_url)


@vessels.route('/vessel_move_contents/<vessel_id>', methods=['GET', 'POST'])
def vessel_move_contents(vessel_id):
    _all_vessels = Vessel.query.join(Vessel.vesseltype_rel) \
        .filter(Vessel.status_id == 100) \
        .filter((Vessel.batch_id.is_(None) | Vessel.batch_id.is_('')))\
        .all()
    _current_vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==vessel_id).first()
    _batch = Batch.query.filter_by(id=_current_vessel.batch_id).first()

    form = VesselMoveContentsForm()

    form.name.choices = [(row.id, row.name) for row in _all_vessels]

    if form.validate_on_submit():
        
        new_vessel_id = form.name.data
        _new_vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==new_vessel_id).first()
        _new_vessel.batch_id = _current_vessel.batch_id
        _new_vessel.status_id = 102 
        _current_vessel.batch_id = ''
        _current_vessel.status_id = 101

        db.session.add(_new_vessel)
        db.session.commit()

        db.session.refresh(_new_vessel)
        flash('Vessel contents moved.', 'success')
        return redirect(url_for('vessels.all_vessels'))
    
    return render_template('vessels/vessel_move_contents.html',
                           form=form,
                           vessel=_current_vessel,
                           batch=_batch)


@vessels.route('/vessel_update_status/<vessel_id>', methods=['GET', 'POST'])
def vessel_update_status(vessel_id):
    _vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==vessel_id).first()
    
    form = VesselUpdateStatusForm(obj=_vessel)

    form.status_id.choices = [(row.id, row.name) for row in Status.query.filter_by(type='Vessel').all()]

    if form.validate_on_submit():
        form.populate_obj(_vessel)
        db.session.add(_vessel)
        db.session.commit()

        db.session.refresh(_vessel)
        flash('Vessel status updated.', 'success')
        return redirect(url_for('vessels.all_vessels'))
    
    return render_template('vessels/vessel_update_status.html',
                           form=form,
                           vessel=_vessel)


@vessels.route('/vessel_fill/<batch_id>', methods=['GET', 'POST'])
def vessel_fill(batch_id):
    _all_vessels = Vessel.query.join(Vessel.vesseltype_rel) \
        .filter(Vessel.status_id == 100) \
        .filter((Vessel.batch_id.is_(None) | Vessel.batch_id.is_('')))\
        .all()
    _batch = Batch.query.filter_by(id=batch_id).first()
    
    form = VesselFillForm()

    form.name.choices = [(row.id, row.name) for row in _all_vessels]

    if form.validate_on_submit():
        _vessel = Vessel.query.join(Vessel.vesseltype_rel).filter(Vessel.id==form.name.data).first()
        _vessel.batch_id = batch_id
        _vessel.status_id = 102 
        db.session.add(_vessel)
        db.session.commit()

        db.session.refresh(_vessel)
        flash('Vessel status updated.', 'success')
        return redirect(url_for('batches.batch_view', name=_batch.name))
    
    return render_template('vessels/vessel_fill.html',
                           form=form,
                           batch=_batch)

app/templates/vessels/vessel_create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Create Vessel</b></h2> 


{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/vessels/vessel_fill.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Fill Vessel</b></h2> 

<p><b>Batch:</b></p>
<p>{{ batch.name }}</p>

<p>Select Vessel to Fill</p>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/vessels/vessel_label.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

{% set link = base_url + '/vessel_lookup/'+ vessel.id|string %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <img src="{{ qrcode(link, box_size=5) }}">
        </div>
        <div class="col-sm-3">
            <p>ID: {{ vessel.id }}</p>
            <p>{{ vessel.name }}</p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/vessels/vessel_move_contents.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Move Vessel Contents</b></h2> 

<p><b>Batch:</b></p>
<p>{{ batch.name }}</p>

<p><b>Current Vessel:</b></p>
<p>{{ vessel.name }}</p>

{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/vessels/vessel_overview.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}

{% block page_content %}
<a id="btn_batch_add" type="button" href="{{ url_for('vessels.vessel_create') }}" class="btn btn-primary">Add Vessel</a>
<div class="container">
    <div class="row mt-5">
      <div class="col-6 offset-3">
        <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Type</th>
                          <th>Volume</th>
                          <th>Status</th>
                          <th>Batch</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% if all_vessels|length > 0 %}
                          {% for vessel in all_vessels %}
                          <tr>
                            <td>{{ vessel.name }}</td>
                            <td>{{ vessel.vesseltype_rel.name }}</td>
                            <td>{{ vessel.vesseltype_rel.volume_max }} gal</td>
                            <td>{{ vessel.status.name }}</td>
                            <td><a href="{{ url_for('batches.batch_view', name=vessel.batch.name) }}">{{ vessel.batch.name }}</a></td>
                            <td><div class="btn-group" role="group" aria-label="Actions">
                              <a style="margin-right: 5px; margin-left: 5px;" class="btn btn-outline-secondary" href="{{ url_for('vessels.vessel_update_status', vessel_id=vessel.id) }}">Edit Status</a>
                              <a style="margin-right: 5px; margin-left: 5px;" class="btn btn-outline-secondary" href="{{ url_for('vessels.vessel_label', vessel_id=vessel.id) }}">Label</a>
                              {% if vessel.batch.id is defined %}
                              <a style="margin-right: 5px; margin-left: 5px;" class="btn btn-outline-secondary" href="{{ url_for('vessels.vessel_move_contents', vessel_id=vessel.id) }}">Move Contents</a>
                              {% endif %}
                            </div>
                          </td>
                          </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <td>No Vessels Added. Please <a href="{{ url_for('vessels.vessel_create')}}">add a vessel</a></td><td></td>
                          </tr>
                        {% endif %}
                      </tbody>
                    </table>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/vessels/vessel_update_status.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}DABL{% endblock %}



{% block page_content %}

<h2 class="h2"><b>Update Vessel Status</b></h2> 

{{ wtf.quick_form(form) }}
{% endblock %}